Branch
alxiw/ivanovsky.ui-11 pull request #1
Opened 2018-10-08 10:04 UTC by alxiw

Домашнее задание по Java 8

2018-10-15 06:53 UTC, saint88 requested changes

2018-10-15 06:53 UTC, saint88 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Зачем тебе мавен в первом дз?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task02/DoubleStackQueueImpl.java
> +            return true;
Это не гарантирует, что твой элемент находится в очереди. Нужно сделать реальный поиск элемента в очереди, а не просто возвращать true

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +                return true;
Это не гарантирует, что элемент реально помещен в очередь. Нужно сделать поиск элемента в очереди, а не просто возвращать true

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +package ru.mail.track.ui11.hw01.task03;
Код работает неверно. При вводе следующей комбинации в очередь:
        doubleStackQueue.add(2, true);
        doubleStackQueue.add(3, true);
        doubleStackQueue.add(0, true);
        doubleStackQueue.add(9, true);

        //2 3 0 9 - это очередь которая получается по входным данным выше

И вызвав несколько раз метод poll:
        System.out.println(doubleStackQueue.poll(true));
        System.out.println(doubleStackQueue.poll(true));
        System.out.println(doubleStackQueue.poll(true));
        System.out.println(doubleStackQueue.poll(true));

Выводится комбинация: 9 0 3 2, а должна быть 2 3 0 9. И так же проверь получение элементов с конца. При добавлении в конец например комбинации 3 4 5, я должен с конца получить 3 4 5, а не 5 4 3

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task04/Solution.java
> +    public static void printReverseList(List list) {
А где тут Iterator ? В задании имелось ввиду list.iterator(). В общем задачку надо переделать

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task05/Solution.java
> +        for (Double itemFirst : list) {
А где тут итератор? В задании сказано можно использовать только list.iterator()

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +        for (int i = 0; i < top.size(); i++) {
Этот цикл вместе с ограничением на 3 можно сделать красиво через лямбду и limit. Так как у тебя есть список факультетов по популярности. Просто возьми тебе из этого списка стрим, сделай limit на 3 и выведи через forEach.

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +        StringBuilder sb = new StringBuilder();
Строчку можно сделать через String.format, а стринг билдер тут не имеет смысла

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +package ru.mail.track.ui11.hw01.task06;
А почему у тебя все статическое?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task05/Solution.java
> +package ru.mail.track.ui11.hw01.task05;
Почему у тебя все статическое?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task04/Solution.java
> +package ru.mail.track.ui11.hw01.task04;
Почему у тебя все статик?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +    public boolean add(Object item, boolean first) {
item будет не Object, так как мы используем Java Generics

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +    public Object poll(boolean first) {
Возвращается не Object, так как мы используем Java Generics

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +package ru.mail.track.ui11.hw01.task07;
Почему все статик?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +    public static void printStringsToCsv(List<String> list, int[] lengths, File path) throws FileNotFoundException {
Я бы сделал длины не через массив целых чисел, а через метод с переменным числом входных параметров: (List<String> list, File file, int... lengths). И параметр типа File это не путь, а файл, а из имени следует, что я должен передать путь к файлу.

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +        for (int l : lengths) {
Перепиши вот это через лямбды и фильтры (надо применить знания на практике =) )

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +public class Solution {
Если нет строки определенной длины, то не нужно выводить ее в файл. Сейчас если указать длины скажем 2,3,4,5 и передать список строк только длин 4, 5, то выводится:
2
3
4 <тут строки длиной 4>
5 <тут строки длиной 5>
А должно выводиться:
4 <тут строки длиной 4>
5 <тут строки длиной 5>

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task08/Solution.java
> +    public static Predicate<Integer> intFunc(int intFunc1) {
А разве в задаче сказано про целые числа что-то? И должна (функциональный интерфейс Function), а не метод

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task08/Solution.java
> +        Predicate<Integer> predicate1 = n -> n > 5;
А что это за числа? В задаче про них не сказано ничего

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task09/Stopwatch.java
> +package ru.mail.track.ui11.hw01.task09;
Где абстрагирование?
Нужно сделать отдельный метод, который будет выводить время, а второй метод, который будет выводить сообщение. Первый метод вызывается в первом потоке, а второй во втором. Так же нужно выводить реально время, а не секунды. А ес ли выводишь секунды, то тогда после 60 секунд, нужно выводить минуты =)
Используй для времени LocalTime.

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task09/Stopwatch.java
> +import java.time.Duration;
И эти методы нужно сделать в отдельном классе и не статическими =)

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +package ru.mail.track.ui11.hw01.task11;
Опять все в одном классе и статично. Абстрагирование где?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +        final PipedInputStream pis = new PipedInputStream();
А зачем ты каналы передачи сделал в методе? Почему не свойства класса?

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +        Thread pipeWriter = new Thread(() -> {
Выдели функциональные границы. Например один метод чтения файла, второй обработки , третий записи в файл. А в main у тебя будет просто передача через pipe

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +                FileWriter writer = new FileWriter(output);
Тут так же надо сделать абстрагирование, как написано выше

2018-10-15 06:53 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +    private static String censor(String line) {
Этот метод явно не должен быть в Main классе, а вынесен в класс обработки

2018-10-15 06:53 UTC, saint88 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Увидел юнит тесты внизу =) В целом тогда понятно зачем тебе мавен проект, но не вижу смысла тогда в остальных зависимостях в нем.

2018-10-15 06:55 UTC, saint88 reviewed
В целом неплохо, но нужно будет поправить комментарии и замечания до конца этой недели, чтобы выставить отметку.

2018-10-15 10:23 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +package ru.mail.track.ui11.hw01.task03;
Разве код не должен работать так же, как обычная двусторонняя очередь, т.е. java.util.Deque?
Исходя из условия задачи, "реализуйте интерфейс двусторонней очереди c использованием стеков", я решил, что решение должно работать в точности, как дэк

2018-10-15 11:05 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task02/DoubleStackQueueImpl.java
> +            return true;
+

2018-10-15 11:07 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +                return true;
Согласен, поправлю

2018-10-15 11:07 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +    public Object poll(boolean first) {
Согласен, поправлю

2018-10-15 11:35 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task04/Solution.java
> +    public static void printReverseList(List list) {
Понял, исправлю

2018-10-15 11:43 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task05/Solution.java
> +        for (Double itemFirst : list) {
Понял, исправлю

2018-10-15 12:34 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +        for (int i = 0; i < top.size(); i++) {
Понял, сделаю

2018-10-15 13:36 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +        StringBuilder sb = new StringBuilder();
Согласен, что через String.format было бы красивее, но мне кажется, что он не очень удобен в том плане, что с ним решение получается не такое гибкое. Если захотим вывести Top 4? Для этого придётся формировать для String.format строку с количеством %s в зависимости от number (количество в топе), а также новый массив значений, которые выводим - это сильно увеличит объём кода и усложнит его. На мой взгляд, решение со StringBuilder позволяет быстрее формировать правильную строку в зависимости от number. 
Что думаешь?

P.S. Пока исправил в строке, чтобы Top был от number, а не выводил всегда 3, а также цикл с ограничением заменил на стрим с лимитом

2018-10-15 13:49 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +    public boolean add(Object item, boolean first) {
Согласен, исправил

2018-10-15 13:51 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +public class Solution {
Исправил

2018-10-15 13:59 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +    public static void printStringsToCsv(List<String> list, int[] lengths, File path) throws FileNotFoundException {
Согласен, поправил

2018-10-15 15:05 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +        for (int l : lengths) {
Что-то пока не очень ясно представляю, как лучше переписать этот цикл с помощью лямбд 
       
    for (int l : lengths) {
        List<String> strings = new ArrayList<>();
        for (Map.Entry entry : map.entrySet()) {
        if (entry.getKey().equals(l))
            strings = map.get(l);
        }
        if (strings.isEmpty()) {
            continue;
        }

        String[] array = new String[strings.size() + 1];
        array[0] = String.valueOf(l);
        for (int i = 1; i < array.length; i++) {
            array[i] = strings.get(i - 1);
        }
        data.add(array);
    }

Пробовал первый вложенный цикл преобразовать, но так не работает
List<String> strings = (List<String>) map.entrySet().stream().filter(x -> x.getKey().equals(l)).map(Map.Entry::getValue);

2018-10-15 19:09 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task08/Solution.java
> +    public static Predicate<Integer> intFunc(int intFunc1) {
Да, подумал, что имеется ввиду метод 🙂
Постараюсь исправить

2018-10-15 19:11 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task08/Solution.java
> +        Predicate<Integer> predicate1 = n -> n > 5;
Исправлю

2018-10-15 20:58 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task09/Stopwatch.java
> +import java.time.Duration;
Исправил

2018-10-15 20:58 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task09/Stopwatch.java
> +package ru.mail.track.ui11.hw01.task09;
Исправил

2018-10-15 21:32 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +    private static String censor(String line) {
Исправил

2018-10-15 21:32 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +                FileWriter writer = new FileWriter(output);
Исправил

2018-10-15 21:32 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +        final PipedInputStream pis = new PipedInputStream();
Исправил

2018-10-15 21:32 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task11/Solution.java
> +package ru.mail.track.ui11.hw01.task11;
Исправил

2018-10-16 06:12 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task03/DoubleStackDequeImpl.java
> +package ru.mail.track.ui11.hw01.task03;
Да согласен. Тогда замечание снимается.

2018-10-16 06:13 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task06/Solution.java
> +        StringBuilder sb = new StringBuilder();
Да согласен. Тогда оставляем стринг билдер =)

2018-10-17 07:25 UTC, saint88 requested changes
Исправь тот кусочек, который я тебе в комментарии написал. И еще надо убрать второе домашнее задание из этой ветки и сделать его в новой ветке. Так как это дз я приму после изменения цикла на стримы и волью в мастер (в мастере только принятые дз).

А в остальном все отлично, молодец. Исправишь цикл, будет за дз 10 из 10 =)

2018-10-17 07:25 UTC, saint88 commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +        for (int l : lengths) {
Смотри. Первое можно переписать как:
   private static List<String> getStringsOfSameLength(Map<Integer, List<String>> strings, int length) {
        Optional<Map.Entry<Integer, List<String>>> options = strings.entrySet().stream()
                .filter(entry -> entry.getKey() == length)
                .findFirst();
        return options.isPresent() ? options.get().getValue() : new ArrayList<>();
    }
Это кстати о вопросах об абстрагировании =)

А вот так можно переписать весь кусочек:
        List<String[]> data =Arrays.stream(lengths)
                .filter(length -> !getStringsOfSameLength(map, length).isEmpty())
                .mapToObj(length -> getStringsOfSameLength(map, length))
                .collect(Collectors.toList()).stream()
                .map(str -> {
                    String[] array = new String[str.size() + 1];
                    array[0] = String.valueOf(str.get(0).length());

                    IntStream.range(1, array.length)
                            .forEach(index -> array[index] = str.get(index - 1));
                    return array;
                }).collect(Collectors.toList());

2018-10-17 07:28 UTC, saint88 commented
Это к 7 заданию, как можно переписать это все на стримы:

        List<String[]> data =Arrays.stream(lengths)
                .filter(length -> !getStringsOfSameLength(map, length).isEmpty())
                .mapToObj(length -> getStringsOfSameLength(map, length))
                .collect(Collectors.toList()).stream()
                .map(str -> {
                    String[] array = new String[str.size() + 1];
                    array[0] = String.valueOf(str.get(0).length());

                    IntStream.range(1, array.length)
                            .forEach(index -> array[index] = str.get(index - 1));
                    return array;
                }).collect(Collectors.toList());   

 private static List<String> getStringsOfSameLength(Map<Integer, List<String>> strings, int length) {
        Optional<Map.Entry<Integer, List<String>>> options = strings.entrySet().stream()
                .filter(entry -> entry.getKey() == length)
                .findFirst();
        return options.isPresent() ? options.get().getValue() : new ArrayList<>();
    }

2018-10-17 09:54 UTC, alxiw commented on src/main/java/ru/mail/track/ui11/hw01/task07/Solution.java
> +        for (int l : lengths) {
Cпасибо, разобрался! 
Кстати, можно ещё подсократить, убрав .collect(Collectors.toList()).stream() поскольку идёт преобразование стрима от списка с списку и затем опять к стриму 🙂

2018-10-17 11:37 UTC, alxiw commented
Забыл, что при переименовании ветки она на удалённом репозитории не переименовывается, а создаётся новая с удалением старой 🙃

P.S. Исправил седьмую задачу и удалил второе задание из данной ветки

2018-10-19 16:39 UTC, merged