HW-02
alxiw/ivanovsky.ui-11 pull request #2
Opened 2018-10-21 22:39 UTC by alxiw

Второе домашнее задание по теме Git + Maven

2018-10-21 22:45 UTC, alxiw commented
Добавил решения первой и второй задачи из второго задания

P.S. Поскольку заливал первую задачу ранее в ветку первого задания (потом удалил оттуда), здесь в пул-реквесте не видны изменения, но в самой ветке она есть

2018-10-23 06:40 UTC, saint88 requested changes
Написана задача отлично, молодец. Немного мелких замечаний, а так отлично.

2018-10-23 06:40 UTC, saint88 commented on homework-02/task-02/src/main/java/ru/mail/track/ui11/hw02/task02/Checker.java
> +    @Option(name="-n", usage="Number of words to read")
Задача класса - обрабатывать строки, а что тут делает описание Options?

2018-10-23 06:42 UTC, saint88 commented
И у тебя конфликт, который надо решить

2018-10-23 07:03 UTC, saint88 requested changes
Надо еще разобраться с путями в первой задаче, почему не пишется результат в файл результата, во второй задаче все работает отлично.

2018-10-23 07:03 UTC, saint88 commented on homework-02/task-01/src/main/java/ru/mail/track/ui11/hw02/task01/KeyKeeper.java
>      private static final int KEYSIZE = 2048;
Первая задача не создает файлы результата после запуска

2018-10-23 07:57 UTC, alxiw commented on homework-02/task-01/src/main/java/ru/mail/track/ui11/hw02/task01/KeyKeeper.java
>      private static final int KEYSIZE = 2048;
В задаче было сказано: данная программа должна уметь шифровать и расшифровывать данные при передачи зашифрованного csv файла. Исходя из этого, я в программе сделал 2 режима: encoding и decoding. Первый запускается через аргумент encode в после имени jar-файла, второй через аргумент decode. Соответственно, запуск с параметром en обработает файл source.csv из папки resources, лежащей рядом с jar-файлом, и создаст так-же рядом папку results с обработанным csv-файлом result. Аналогично с режимом декодирования, только файл будет взят из results, а обработанный фал будет помещён в reverses

2018-10-23 12:12 UTC, alxiw commented on homework-02/task-02/src/main/java/ru/mail/track/ui11/hw02/task02/Checker.java
> +    @Option(name="-n", usage="Number of words to read")
Понял, вынесу в отдельный класс

2018-10-23 18:11 UTC, saint88 commented on homework-02/task-01/src/main/java/ru/mail/track/ui11/hw02/task01/KeyKeeper.java
>      private static final int KEYSIZE = 2048;
Понял, не увидел. Тогда просто отлично.

2018-10-23 18:12 UTC, saint88 approved these changes

2018-10-23 18:13 UTC, merged

2018-10-23 18:13 UTC, saint88 commented
Отлично. За дз 10 баллов из 10