HW-03
alxiw/ivanovsky.ui-11 pull request #3
Opened 2018-10-29 13:39 UTC by alxiw

Третье домашнее задание по теме JUnit 4 + Hamcrest + Mockito

2018-10-30 15:39 UTC, saint88 requested changes
Нужно разобраться и поправить падающие тесты. Они падать не должны

2018-10-30 15:39 UTC, saint88 commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToTen() {
Тест падает, хотя не должен

2018-10-30 15:39 UTC, saint88 commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToTwo() {
Тест падает

2018-10-30 15:39 UTC, saint88 commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToOneHundred() {
Тест падает

2018-10-30 16:59 UTC, alxiw commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToTen() {
При каких параметрах запуска происходит падение?
При запуске с помощью mvn install -P full-test -Dthread.count=8 успешно проходят все 22 теста

2018-10-30 22:23 UTC, alxiw commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToOneHundred() {
В общем, понял в чём дело. Если в surefire-плагине выставлять различные параметры для тредов, то действительно тесты падают, а именно возникают коллизии при попытках синхронизированно подменять переменную System.out, выводить сроку, после чего сбрасывать System.out в дефолтное значение. Но поскольку в задаче сказано о необходимости вывода простых чисел от 0 до N, добавил в метод printAllPrimes(int n) строку возврата. Тесты поправил в соответствии со сравнением теперь этой строки с expected значением.

2018-10-30 22:23 UTC, alxiw commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToTwo() {
Исправил

2018-10-31 08:47 UTC, saint88 commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToTen() {
Сейчас уже проходят. Там проблема была в спец символах \n\r

2018-10-31 08:47 UTC, saint88 commented on homework-03/src/test/java/ru/mail/track/ui11/hw03/task01/SievePositiveTest.java
> +    public void printPrimesToOneHundred() {
Отлично. Молодец.

2018-10-31 08:48 UTC, merged

2018-10-31 08:48 UTC, saint88 commented
За дз 10 баллов. Молодец.