HW-04
alxiw/ivanovsky.ui-11 pull request #4
Opened 2018-11-29 19:37 UTC by alxiw

Четвёртое домашнее задание по теме Selenium API

2018-11-30 06:40 UTC, saint88 requested changes
А где остальные кейсы? В задании написано, автоматизировать все кейсы из презентации. В презентации я насчитал вроде 3 задачи (3 кейса). ТЫ сделал только 1 с гуглом. Осталось 2.

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/ArticlePage.java
> +@Domain("https://test.mail.ru")
Почему тут домен test.mail.ru?

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/ArticlePage.java
> +    public ArticlePage checkPageUrl() {
Этот метод не нужно вызывать явно, а он должен вызываться автоматически в методе open() после открытия страницы

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='resultStats']")
id в доме уникален и не может повторяться у элементов, так зачем писать css, когда можно и лучше использовать стратегию поиска id

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='search'] > div > h1")
лучше сделать так #search h1 или что-то мне подсказывает, что на странице один элемент заголовка первого уровня h1 и можно использовать просто селектор "h1"

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='navcnt']")
поиск по id, а не css

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    public GoogleMainPage typeSearchText(String text) {
Ты тут сделал сабмит и теперь этот метод не вводит текст. Раздели и скрой метод сабмита и метод ввода текста, а открой один метод, который назови typeSearchRequestAndSubmit(String request)

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    public GoogleMainPage pageWithSearchShallBeOpened() {
Вот такие методы лучше делать на BasePage, чтобы их можно было вызвать с любой страницы

2018-11-30 06:40 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/ArticlePageTest.java
> +    public void check_url_of_article_page() {
А что у тебя этот тест проверяет? Такого кейса в презентации нет

2018-11-30 12:10 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='navcnt']")
ОК, исправил

2018-11-30 12:10 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    public GoogleMainPage typeSearchText(String text) {
ОК, исправил

2018-11-30 12:12 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='search'] > div > h1")
Исправил, заголовок "h1" оказался в данном случае излишним, лучше искать по id, затем проверять на visibility

2018-11-30 12:13 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    @FindBy(css = "div[id='resultStats']")
ОК, исправил

2018-11-30 12:17 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/ArticlePage.java
> +@Domain("https://test.mail.ru")
Для проверки работы создания url с параметрами, относящегося ко второй задаче задания

2018-11-30 12:18 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/ArticlePageTest.java
> +    public void check_url_of_article_page() {
Проверяет правильность построения url по параметрам, заданным в аннотации

2018-11-30 13:18 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/GoogleMainPage.java
> +    public GoogleMainPage pageWithSearchShallBeOpened() {
Согласен, поправил

2018-11-30 13:18 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/ArticlePage.java
> +    public ArticlePage checkPageUrl() {
Согласен, поправил

2018-12-05 08:23 UTC, saint88 requested changes
Надо поправить метод выбора пола и вливаем

2018-12-05 08:23 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/pages/NameSecretHoroMailPage.java
> +    public NameSecretHoroMailPage selectGenderInMenu() {
А почему этот метод выбирает пол только женский. Пол нужно передавать в сигнатуре метода. И потом это поле - <select> и с ним нужно работать через класс Select.

2018-12-05 08:23 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .selectGenderInMenu()
Этот метод должен выбирать пол, как я понял, но он всегда выбирает женский пол. Нужно в общем передавать пол через параметры метода

2018-12-05 12:22 UTC, merged