HW-05
alxiw/ivanovsky.ui-11 pull request #5
Opened 2018-12-06 21:06 UTC by alxiw

Пятое домашнее задание по теме Selenium API

2018-12-07 09:37 UTC, saint88 requested changes
Нужно поправить замечания

2018-12-07 09:37 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Этот метод не нужно вызывать после опена, так как он должен вызываться в самом open()

2018-12-07 09:37 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Аналогично выше

2018-12-07 09:37 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Аналогично выше

2018-12-07 09:37 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Аналогично выше

2018-12-07 09:37 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NewsPetsMailPageTest.java
> +                .pageShallBeOpened()
Аналогично выше

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +@PageUrl("/")
Почему у тебя PageUrl("/"). Он по такому урлу должен открыть главную: домен + "/". А у тебя шаблон на валидаторе страницы /prognoz/[\\w]{1,20}. Т.е. получается что-то не сходится.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(css = "span[class=\"pm-toolbar__suggests__group__item  pm-toolbar__suggests__group__item_with-caption\"]:first-child > span > span > span:first-child")
можно вместо двойных кавычек в локаторе, использовать одинарные кавычки, чтобы в стринге не экранировать их.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(xpath = "//div[@class='information__header__left__place']/h1[text()='Киев']")
А зачем тут харкодить город Киев. Его нужно передавать как параметр в локатор, потому что прийдет кейс на тестирование города внутри страны и все, будем писать новый локатор и метод.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(css = "span[class=\"icon icon_fav-flag js-toggle_fav\"]")
Тут тоже лучше использовать одинарные кавычки, чтобы не экранировать. И такой селектор не пойдет. Вот пересоберут верстку и поменяют местами классы и все, локатор работать не будет. В общем его надо переписать.
Главные условия к локаторам: находит только нужные элементы на странице (уникальность) и адаптируемый к мелким изменениям на верстке, например смена порядка следования классов в элементе.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    private final String cityInFavorites = "//span[@class='city-select__item clearfix city-select__item_current']//span[@class='city-select__item__city']";
Аналогично выше. Локатор такой не пойдет

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +@PageUrl("/prognoz/easter_island/10-june/#2015")
Зачем харкод? Вот тут нужно дату передавать в урл. Дату передавать нужно через LocalDate

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    @FindBy(xpath = "//span[contains(@class, 'calendar__control_next')]")
Точно такой же элемент написан выше, только в локаторе prev вместо next. Нужно сделать один общий локатор для кнопок навигации и передавать туда NavigationData. В enum определить что-то типа такого:
Next(">"),
Prev("<")

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    @FindBy(xpath = "//div[contains(@class, 'heading heading_minor heading_line')]")
Локатор переписать. Написал почему выше

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    public CalendarPogodaMailPage goToNextMonth() {
Такой метод уже есть выше. Этот надо убрать и сделать единый метод с передачей NavigationData

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +        driver.findElement(By.xpath("//table[contains(@class, 'calendar')]//a[text() = '" + day + "']")).click();
Такой локатор надо хранить в виде шаблона для String.format и как поле класса private final String

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    public CalendarPogodaMailPage checkDayInList(String month, int day) {
Для работы с датами есть LocalDate, ее и надо передавать сюда

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +        String regex = day + "\\s" + firstThreeLettersOfMonthName + "\\W*\\s\\d{4}";
Старайся все таки использовать String.format для таких штук. Более наглядно получается

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +        assessment = assessmentElement.findElement(By.xpath("//span[contains(@class, 'link__text margin_right_5')]")).getText();
Локаторы не нужно хранить в методе, так как на этапе поддержки тестов потом тяжело будет понять где и какой элемент юзается. Так же такой локатор совсем не пойдет, причину написал выше. Надо его переписать. И еще не стоит использовать классы типа margin_right_5, как пример, так как это автоматически генерируемые классы.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +        assertTrue("Заголовок выпадающего окна не содержит названия параметра \"" + assessment + "\"",
String.format будет лучше

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +@PageUrl("/catalog/ford/focus/iii_restailing/sedan/")
машину передавать так хардкором не стоит. Так как завтра она может уже использоваться другая. Лучше передавай через параметры следующие параметры автомобиля: ford, focus, iii_restailing и sedan. Т.е. сюда будет передаваться что-то типа такого "/catalog/%1/%2/%3/%4"

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task04/NewsSportMailPage.java
> +@PageUrl("/news/football-worldcup/32246552/")
Этот id надо передавать через параметры. Хранить надо в виде Enum. Я бы создал два перечисления. Один для типа игр футбола и там хранил football-worldcup в виде Football_worldcup("Чемпионат мира"), а вот во втором enum хранил бы CherkesovVybiraetSbornuyu("Так Черчесов будет выбирать состав сборной России на чемпионат мира", FootballType.Football_worldcup, 32246552). Таким образом ты связываешь параметры статьи отношением один ко многим.А в метод передавать enum с заголовком статьи и id

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPage.java
> +@PageUrl("/how-to/nyanya-dlya-sobak-i-koshek-kak-podgotovitsya-k-raz/")
Не нужно харкодить название статьи, а нужно передавать через параметры

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPage.java
> +    @FindBy(xpath = "//time")
tagName="time"

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task01/PogodaMailPageTest.java
> +                .pageShallBeOpened()
Этот метод должен вызываться в опен

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .checkMonthInCalendar("Июнь")
Через LocalDate

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .pageShallBeOpened()
Должен вызываться в open()

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .checkMonthInCalendar("Май")
Через LocalDate

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .checkMonthInCalendar("Июнь")
Через LocalDate

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .goToNextMonth()
В этот метод нужно передавать кнопку навигации

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .goToPrevMonth()
Передавать надо в метод кнопку навигации

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task03/CarsMailPageTest.java
> +                .pageShallBeOpened()
вызываться должен в методе open()

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task04/NewsSportMailPageTest.java
> +    public void check_error_on_news_sport_page() {
Я так понимаю это тест напроверку рекламных слотов, а где проверка этих слотов? Смотри если ты откроешь страничку, которая указана в кейсе и откроешь https://s.mail.ru/5bkc/nC4FCcDHC, то там в параметрах запроса передаются рекламные слоты. Так вот, чтобы их получить, тебе нужно включить сниффинг трафика на драйвере. Потом получить трафик и проверить, что у тебя в трафике есть вызовы тех рекламных слотов, которые указаны в кейсе. Должен быть метод, который принимает рекламные слоты и их параметры и проверяет их наличие. Но есть одно НО, драйвер складывает трафик в буфер и после получения его из этого буфера, он очищается. Поэтому тебе нужно получить весь трафик и потом его анализировать.

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task04/NewsSportMailPageTest.java
> +        new NewsSportMailPage(driver)
Тест не соответствует кейсу и его надо переписать

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task04/NewsSportMailPageTest.java
> +        new NewsSportMailPage(driver)
@Step("Получаем трафик страницы")
    private List<Map<String, ?>> getPerformanceLogEntryByDomain(String domain, String method) {
        List<LogEntry> entries = getDriver().manage().logs().get(LogType.PERFORMANCE).filter(Level.ALL);

        return entries.parallelStream().filter(log -> log.getMessage().contains(domain) && log.getMessage().contains(method))
                .map(LogEntry::toJson).collect(Collectors.toList());
    }

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task04/SportMailPageTest.java
> +    public void check_error_on_sport_page(){
Этот тест не понятно что проверяет, но если рекламные слоты, то нужно сделать как написано выше и в одном тесте открывать сначала одну страничку, а потом другую

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPageTest.java
> +                .pageShallBeOpened()
Должен вызываться в методе open()

2018-12-07 09:37 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPageTest.java
> +                .checkExistenceOfPublicationTime();
Вот тут неправильно так проверять. Ты проверяешь, что у тебя элемент виден на странице, но не проверяешь, что это дата (ее формат) и что текст в этом элементе не пустой, а ведь может же отображаться null например в элементе (поэтому надо проверить формат даты) или может вообще быть пусто, хотя сам элемент отображается на страничке (поэтому нужно проверять, что текст в элементе не exist). Хотя думаю если ты проверишь, только формат даты, то этого будет вполне достаточно.

2018-12-07 09:37 UTC, saint88 commented on homework-05/pom.xml
> +            <groupId>ru.mail.track.ui11</groupId>
Сейчас так пойдет, но в реальной работе нужно выносить в отдельный мавен проект и зависимость делать на него, чтобы не тянуть кучу модулей, которые не имеют никакого отношения к данному модулю. Но вообще молодец =)

2018-12-08 15:08 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    private final String cityInFavorites = "//span[@class='city-select__item clearfix city-select__item_current']//span[@class='city-select__item__city']";
В чём проблема такого локатора? Мы же находимся на странице города, который только-что выбрали и добавили в "Избранное", и теперь ищем его в выпадающем списке по наличию в названии класса "city-select__item_current

2018-12-08 15:10 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(xpath = "//div[@class='information__header__left__place']/h1[text()='Киев']")
Да, согласен 😊 
Исправил

2018-12-08 15:10 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(css = "span[class=\"pm-toolbar__suggests__group__item  pm-toolbar__suggests__group__item_with-caption\"]:first-child > span > span > span:first-child")
Исправил

2018-12-08 15:15 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +@PageUrl("/")
Дело в том, что мы переходим по URL "/", но система сразу-же перебрасывает на страницу дефолтного города "/prognoz/<city_name>/", после чего срабатывает механизм проверки URL открытой страницы по шаблону регулярного выражения

2018-12-08 15:19 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
В методе данная проверка присутствует, но забыл про неё, поэтому написал этот дублирующий метод 🙂
В общем, он не нужен, убрал его

2018-12-08 15:19 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-08 15:19 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-08 15:19 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NameSecretHoroMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-08 15:19 UTC, alxiw commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/NewsPetsMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-08 15:20 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +    @FindBy(css = "span[class=\"icon icon_fav-flag js-toggle_fav\"]")
Исправил

2018-12-08 16:40 UTC, alxiw commented on homework-05/pom.xml
> +            <groupId>ru.mail.track.ui11</groupId>
Вынесу тогда лучше эту основу из HW-04 в отдельный модуль и добавлю dependency на него в HW-04 и HW-05

2018-12-08 17:29 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +@PageUrl("/prognoz/easter_island/10-june/#2015")
ОК, исправил

2018-12-08 18:00 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    @FindBy(xpath = "//span[contains(@class, 'calendar__control_next')]")
Исправил

2018-12-08 18:15 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    @FindBy(xpath = "//div[contains(@class, 'heading heading_minor heading_line')]")
Переписал

2018-12-08 18:47 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    public CalendarPogodaMailPage goToNextMonth() {
Исправил

2018-12-08 18:48 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +    public CalendarPogodaMailPage checkDayInList(String month, int day) {
Исправил

2018-12-08 18:48 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +        String regex = day + "\\s" + firstThreeLettersOfMonthName + "\\W*\\s\\d{4}";
Хорошо, везде поправил на него

2018-12-08 20:47 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +        assertTrue("Заголовок выпадающего окна не содержит названия параметра \"" + assessment + "\"",
Исправил

2018-12-08 20:47 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +@PageUrl("/catalog/ford/focus/iii_restailing/sedan/")
Исправил

2018-12-08 21:14 UTC, alxiw commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +        assessment = assessmentElement.findElement(By.xpath("//span[contains(@class, 'link__text margin_right_5')]")).getText();
Исправил

2018-12-08 21:32 UTC, alxiw commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPageTest.java
> +                .checkExistenceOfPublicationTime();
Исправил

2018-12-08 21:33 UTC, alxiw commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .goToNextMonth()
Написал выше

2018-12-08 21:33 UTC, alxiw commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .goToPrevMonth()
Написал выше

2018-12-08 21:33 UTC, alxiw commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task03/CarsMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-08 21:33 UTC, alxiw commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task05/ArticlePetsMailPageTest.java
> +                .pageShallBeOpened()
Написал выше

2018-12-09 18:02 UTC, saint88 requested changes
Надо поправить локаторы. Не нужно привязываться к порядку следования классов в элементе. И до поправлять остальные замечания.

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task02/NewsPetsMailPage.java
> +    private String newsFieldSelector = "[class='pypo-item js-pgng_item']";
Если поменяются классы местами, то этот селектор работать не будет. Надо его поменять

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task02/NewsPetsMailPage.java
> +    private String showMoreButtonSelector = "[class='button js-pgng_more_link']";
Аналогично выше

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String suggestNamesLocator = "//div[@class='newsitem newsitem_vertical newsitem_special newsitem_border_bottom']";
Если поеняют классы местами, то этот xpath работать не будет. Надо его поменять

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String nameInfoElement = "//div[@class='newsitem newsitem_vertical newsitem_namesecret']";
Аналогично выше

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String letterOpenButtonSelector = "[class='filter__item filter__item_active']";
аналогично выше

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String suggestElementLocator = "//div[@class ='suggest__item js-suggest__item']";
аналогично выше

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String genderSelectLocator = "//div[@class ='dropdown dropdown_scrollable dropdown_scrollable dropdown_scrollable js-select js-module']";
Аналогично выше

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +    private String genderListLocator = "//div[@class ='suggest__inner js-select__options__list js-scrollable__view dropdown__scroll']";
Аналогично выше. Не нужно привязываться к следованию значений атрибутов элемента. Поищи уникальные классы или комбинации. Они могут находиться так же в элементах ниже или выше. Надо переписать этот локатор

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task03/NameSecretHoroMailPage.java
> +        String womanSelectElementLocator = String.format("//div[@class ='suggest__item js-select__options__item' and text()='%s']", gender);
Это плохой локатор, аналогично как написано выше. Так же локаторы лучше выносить в свойства объекта страницы и инкапсулировать (PageObject) и не нужно хранить их в методах, так как они могут понадобиться в других методах или например могут быть частью других локаторов. Да и поддерживать такие локаторы намного проще и легче.

2018-12-09 18:02 UTC, saint88 commented on homework-04/src/test/java/ru/mail/track/ui11/hw04/task04/ArticlePageTest.java
> +                .open("articles", "some")
А что этот тест проверяет? В задании же написано, что нужно проверять наличие рекламных слотов в параметрах запроса. Я даже тебе скриншот прислал. Посмотри в лекциях тему как включить сниффер трафика на драйвере. Так же получи запросы (тоже писал в слаке) и затем проверь, что когда открывается страничка, то у тебя есть запрос с теми параметрами (номер слота, site_id и т.д.), которые указаны в кейсе из дз.

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +@PageUrl("/")
Хорошо. Тогда отлично и оставляем так

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +        String firstSuggestedCity = String.format("//span[@class='pm-toolbar__suggests__group__item  pm-toolbar__suggests__group__item_with-caption']//span[text()='%s']", city);
Во первых локатор такой не пойдет, написал причину выше. Во вторых не нужно хранить локаторы в методе, а нужно хранить их в свойствах объекта страницы (паттерн PageObject)

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task01/PogodaMailPage.java
> +                        ExpectedConditions.visibilityOf(driver.findElement(By.xpath(String.format("//div[@class='information__header__left__place']/h1[text()='%s']", city)))))));
все локаторы должны быть свойствами объекта страницы. И еще проверь локатор //h1, что-то мне подсказывает, что на странице всего лишь один заголовок первого уровня и твой локатор очень сложный и перегруженный

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPage.java
> +        driver.findElement(By.xpath(String.format("//table[contains(@class, 'calendar')]//a[text() = '%d']", day))).click();
не нужно хранить локаторы в методе, лучше их сделать в свойствах объекта страницы

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task03/CarsMailPage.java
> +    @FindBy(xpath = "//span[contains(text(), 'Плюсы')]/following::span[contains(text(), 'Управляемость')][1]")
А для минусов нельзя использовать этот же локатор, только с другими данными в шаблоне вместо "Плюсы" и "Управляемость"? А то получается у нас для каждого параметра мы будем писать одинаковые локаторы. В общем локатор должен быть динамический и параметры надо передавать через enum

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/main/java/ru/mail/track/ui11/hw05/task04/NewsSportMailPage.java
> +@PageUrl("/news/football-worldcup/32246552/")
Не исправлено

2018-12-09 18:02 UTC, saint88 commented on homework-05/src/test/java/ru/mail/track/ui11/hw05/task02/CalendarPogodaMailPageTest.java
> +                .open("prognoz", "easter_island",
в тесте не стоит делать таку логику. Лучше ее сделать на пейдже. И там уже делай эту логику. А в самом тесте должен быть просто вызов метода open("easter_island", first)

2018-12-09 21:14 UTC, alxiw commented on homework-04/src/main/java/ru/mail/track/ui11/hw04/task02/NewsPetsMailPage.java
> +    private String newsFieldSelector = "[class='pypo-item js-pgng_item']";
И на что в данном случае, например? Тут же не Google, тут нет у всех значимых элементов уникальных имён или id

2018-12-15 22:48 UTC, alxiw commented
Исправил селекторы в четвёртом и пятом заданиях, а также улучшил следование паттерну Page Object
Проверку логов обращения по сети решил пока отложить, поскольку приоритетнее сейчас остальные ДЗ с проектом, но если до экзамена время останется, то обязательно вернусь к этому вопросу

2018-12-17 06:12 UTC, saint88 approved these changes
Все отлично. Ставлю 8 баллов, так как нет задачи с логами. Сделаешь ее, если время останется, исправлю на 10. Но 8 баллов это тоже отлично.

2018-12-17 06:12 UTC, merged