UI-FW
alxiw/ivanovsky.ui-11 pull request #8
Opened 2018-12-17 21:46 UTC by alxiw

Задания финального проекта по курсу Технотрека "Автоматизированное Тестирование"

2018-12-18 08:17 UTC, saint88 requested changes
Нужно поправить все замечания в выпускном проекте. Так же завтра перед экзаменом нужно будет мне показать как работают эти тесты в селеноиде и запускаются через дженкинс (это дз 8 и плюс часть баллов за итоговый проект)

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task01/PredictionHoroMailPage.java
> +        boolean a = birthdayString.contains(date.getMonth().getDisplayName(TextStyle.FULL, new Locale("ru")).substring(0, 3).toLowerCase());
Какие-то странные имена переменных

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task01/PredictionHoroMailPage.java
> +        boolean a = birthdayString.contains(date.getMonth().getDisplayName(TextStyle.FULL, new Locale("ru")).substring(0, 3).toLowerCase());
И зачем тебе так проверять равенство дат? У объекта LocalDate есть метод isEquals(). Получаешь дату (LocalDate) на странице после клика и сравниваешь с датой, которую сохранил

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/ArticleDetiMailPage.java
> +    private final String headerSelector = "//div[@data-module='BreadcrumbAdmin']/following-sibling::*//h1";
Зачем такой сложный локатор, когда там заголовок первого уровня один на странице. Надо локатор упростить

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/ArticleDetiMailPage.java
> +    private final String headerSelector = "//div[@data-module='BreadcrumbAdmin']/following-sibling::*//h1";
И почему его сразу не хранить в виде SelenideElement?

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    private final String newsSelector = "//*[text()='Новости']/ancestor::*[contains(@class, 'inner')]/following-sibling::*/span";
В ленте может не быть раздела новостей. Такие штуки надо проверять по другому. Получаешь с верстки имя категории, например новости или общение. В данном случае категория первой плитки в ленте - новости. Хранишь категории в виде enum в котором хранишь имя категории и класс странички на эту категорию. Например: News("Новости", NewsPage.class). По имени полученной категории из enum получаешь класс странички категории. Создаешь объект этой страницы и вызываешь нужные тебе степы у страницы.

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    private final String newsSelector = "//*[text()='Новости']/ancestor::*[contains(@class, 'inner')]/following-sibling::*/span";
Если же привязаться к категории новости, то получается у тебя может возникнуть ситуация, когда такой категории в ленте может и не быть

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPageTest.java
> +                .checkHeader();
А где вызов метода проверки урла паттерну страницы? Что мы открыли страницу нужной категории? И обрати внимание, что после клика на плитку смарт ленты у тебя в урле передается параметр запроса from=smartlenta. Его бы было неплохо тоже проверять.

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    public ArticleDetiMailPage clickNewsItem(int index) {
Смарт лента является компонентом и должна быть в отдельном классе с соответствующими валидаторами

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task01/HoroMailPageTest.java
> +                .checkCaptions(Capture.NUMBER.getName(), Capture.RUNA.getName(), Capture.MOON.getName(), Capture.CARD.getName());
А где проверка, что отображен знак зодиака, который соответствует дате

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    private final String newButtonSelector = "//span[contains(text(), 'новые')]/ancestor::a";
Это два одинаковых локатора и принадлежат они одному и тому же компоненту, только разница у них в том, что текст немного разный. Поэтому нужно сделать один локатор и один метод в который передавать вкладку фильтра. И вынести этот фильтр в отдельный компонент с соответствующими валидаторами, так как на других страницах этот фильтр точно такой же

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +@PageUrl("/recipe/week/rating/")
rating является параметром URL и должен в него передаваться

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(popButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
порядок классов может измениться

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(popButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
и зачем тут таймаут нужен в 1000 мс?

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(newButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
Этот метод написан выше

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(popButtonSelector)).click();
Этот метод написан выше

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    }
Не вижу метода проверки, что список рецептов изменился. Этот степ как раз принадлежит данной странице. Т.е. нужно получить список до клика по вкладке и потом после клика проверить, что список рецептов изменился

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPageTest.java
> +                .checkPopViewIsActive()
Этот метод и ниже - методы компонента фильтра, а не страницы

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPageTest.java
> +    }
Где проверка, что после клика по вкладке фильтра содержимое страницы изменилось?

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    public RecipeLadyMailPage checkPopViewIsActive() {
В метод нужно передавать тип вкладки

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/ConsultantPetsMailPage.java
> +    private final String headerSelector = "//h1";
Заголовок это статический локатор и имеет смысл его хранить в виде FindBy и получать на этапе инициализации страницы SelenideElement

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPage.java
> +    private final String consultantSelector = "//*[contains(@class, 'selected')]//*[contains(@class, 'consultant')]/a";
Блок консультантов - компонент

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPage.java
> +    public ConsultantPetsMailPage clickAnyConsultantOnThePage() {
Этот метод должен быть в классе компонента блока консультаций

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPageTest.java
> +                .clickAnyConsultantOnThePage()
Это метод не страницы, а компонента блока консультантов

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task05/ArticlePogodaMailPage.java
> +        Selenide.sleep(3000);
Никаких слипов. Нужно через ожидание ждать пока на странице не будет количество окон больше текущего значения, в твоем случае 2

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task05/ArticlePogodaMailPage.java
> +        WebDriver a = Selenide.switchTo().window(1);
Лучше делать свитч через хэндлер (он уникальный для каждого окна). Так же такие переключения лучше сделать в отдельном классе, например назови его WindowsHelper. Его задача будет переключение на новое окно и обратно

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task05/ArticlePogodaMailPage.java
> +        Selenide.switchTo().window(0);
Переключаться обратно надо в блоке try-finally, чтобы гарантировать, что ты переключишься обратно

2018-12-18 08:17 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task05/PogodaMailPageTest.java
> +                .closeArticleWindow();
А где проверка, что после клика открыта страница проекта, по которому ты кликнул. Я бы проверил что домен отличается от текущего (что это не погода) и что открытая страница вернула код 200, а не 404 или 403

2018-12-18 17:34 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task01/PredictionHoroMailPage.java
> +        boolean a = birthdayString.contains(date.getMonth().getDisplayName(TextStyle.FULL, new Locale("ru")).substring(0, 3).toLowerCase());
Исправил

2018-12-18 17:35 UTC, alxiw commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task01/HoroMailPageTest.java
> +                .checkCaptions(Capture.NUMBER.getName(), Capture.RUNA.getName(), Capture.MOON.getName(), Capture.CARD.getName());
Исправил

2018-12-18 17:47 UTC, alxiw commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPageTest.java
> +                .checkHeader();
Исправил

2018-12-18 17:47 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/ArticleDetiMailPage.java
> +    private final String headerSelector = "//div[@data-module='BreadcrumbAdmin']/following-sibling::*//h1";
Исправил

2018-12-18 19:05 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    private final String newsSelector = "//*[text()='Новости']/ancestor::*[contains(@class, 'inner')]/following-sibling::*/span";
Исправил, добавив компонент SmartBand, внутри которого теперь ищу плитки

2018-12-18 19:45 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    public ArticleDetiMailPage clickNewsItem(int index) {
Добавил для смарт-ленты отдельный компонент

2018-12-18 22:59 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/ConsultantPetsMailPage.java
> +    private final String headerSelector = "//h1";
Исправил

2018-12-18 23:05 UTC, alxiw commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPageTest.java
> +    }
Исправил

2018-12-19 00:47 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task05/ArticlePogodaMailPage.java
> +        Selenide.sleep(3000);
Исправил

2018-12-19 00:47 UTC, alxiw commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task05/PogodaMailPageTest.java
> +                .closeArticleWindow();
Исправил

2018-12-19 00:48 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    public RecipeLadyMailPage checkPopViewIsActive() {
Исправил

2018-12-19 00:48 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    }
Исправил

2018-12-19 00:48 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(popButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
Исправил

2018-12-19 00:48 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(popButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
Исправил

2018-12-19 00:49 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +        $(By.xpath(newButtonSelector)).waitUntil(Condition.attribute("class", "filter__item filter__item_active"), 1000);
Исправил

2018-12-19 00:49 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +@PageUrl("/recipe/week/rating/")
Исправил

2018-12-19 00:49 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/RecipeLadyMailPage.java
> +    private final String newButtonSelector = "//span[contains(text(), 'новые')]/ancestor::a";
Исправил

2018-12-19 00:58 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPage.java
> +    private final String consultantSelector = "//*[contains(@class, 'selected')]//*[contains(@class, 'consultant')]/a";
Исправил

2018-12-19 00:58 UTC, alxiw commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPage.java
> +    public ConsultantPetsMailPage clickAnyConsultantOnThePage() {
Исправил

2018-12-19 00:58 UTC, alxiw commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPageTest.java
> +                .clickAnyConsultantOnThePage()
Исправил

2018-12-19 07:58 UTC, saint88 approved these changes
В принципе немного мелких замечаний, а так все норм. Ставлю в общем 95 баллов за выпускной проект. Если сегодня покажешь как работает в селеноиде (+10 баллов) и за запуск с дженкинса тоже +10 баллов.

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/ArticleDetiMailPage.java
> +@UrlPattern("http[s]?://deti.mail.ru/[\\w_\\-]+/[\\w_\\-]+/\\?from=smartlenta")
Параметр from=smartlenta не всегда есть в урле страницы. Нужно его проверять не на странице, а сделать отдельную проверку в AnyPage, которая бы проверяла, что в URL страницы есть определенные GET параметр

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPage.java
> +    public SmartBand findSmartBand() {
А зачем этот метод? В тесте нужно просто создать объект SmartBand и все. Не нужно связывать страницу и компонент

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task03/AbstractRecipeLadyMailPage.java
> +        if (a instanceof RatingRecipeLadyMailPage && tab.equals(Tab.NEW)) {
Так тоже пойдет, но лучше и красивее сделать было через дженерики

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/main/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPage.java
> +    public Slider findSlider() {
Не нужно делать такие методы. Написал выше

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task02/DetiMailPageTest.java
> +                .findSmartBand()
Такой метод тут не нужен. Можно в тесте просто создать объект компонента и все

2018-12-19 07:58 UTC, saint88 commented on ui-final-work/src/test/java/ru/mail/track/ui11/uifinalwork/task04/PetsMailPageTest.java
> +                .findSlider()
Аналогично как написано выше

2018-12-19 07:58 UTC, saint88 commented
И того получится итоговая отметка 115 баллов за выпускной

2018-12-19 07:58 UTC, merged